// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAH7FGp04DGVW8SFui6Zn1oyfpY7kj7Cc',
    appId: '1:823358857557:web:c8e077cac2652c84424fdc',
    messagingSenderId: '823358857557',
    projectId: 'whatsapp-clone-7255b',
    authDomain: 'whatsapp-clone-7255b.firebaseapp.com',
    storageBucket: 'whatsapp-clone-7255b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4MxG7SEhvwgs5BLo_-hIVJuHSkfl-8x0',
    appId: '1:823358857557:android:065e9fd596486936424fdc',
    messagingSenderId: '823358857557',
    projectId: 'whatsapp-clone-7255b',
    storageBucket: 'whatsapp-clone-7255b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4sl7A1QA-tLtB8vcyt8tZsI1UKMzJ9jA',
    appId: '1:823358857557:ios:202764ef168300fc424fdc',
    messagingSenderId: '823358857557',
    projectId: 'whatsapp-clone-7255b',
    storageBucket: 'whatsapp-clone-7255b.appspot.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
